/* ============================================================
   CALCROO — EXPORT MODEL (pure, English)
   Chuẩn hoá kết quả tính thuế thành một model để engine
   Excel / PDF dùng chung. Luôn tiếng Anh — hồ sơ vay nhà và
   kế toán ở Úc dùng tiếng Anh, và tránh phải nhúng font Unicode
   vào jsPDF.
   ============================================================ */

import { SUPER } from './tax';
import { ALLOCATION_COLORS, ALLOCATION_LABELS_EN } from './allocation';

const money = (n) =>
  (n < 0 ? '-$' : '$') + Math.round(Math.abs(n)).toLocaleString('en-AU');

const pct = (r) => (r * 100).toFixed(1) + '%';

/**
 * @param {{
 *   alloc: import('./allocation').incomeAllocation extends never ? object : object,
 *   withHecs: boolean, withMedicare: boolean, fyLabel: string
 * }} args
 */
export function buildIncomeExportModel({ alloc, withHecs, withMedicare, fyLabel }) {
  const superPct = Math.round(SUPER.sgRate * 100);

  const rows = [
    { key: 'gross', label: 'Gross salary (excl. super)', annual: alloc.salary, kind: 'input' },
    { key: 'super', label: `Superannuation (${superPct}%, employer-paid)`, annual: alloc.super, kind: 'super' },
    { key: 'tax', label: 'Income tax (after LITO)', annual: -alloc.tax, kind: 'value' },
    { key: 'lito', label: 'Low income tax offset (LITO)', annual: alloc.offset, kind: 'offset', show: alloc.offset > 0.5 },
    { key: 'medicare', label: 'Medicare levy', annual: -alloc.medicareLevy, kind: 'value', show: withMedicare && alloc.medicareLevy > 0.5 },
    { key: 'hecs', label: 'HECS-HELP repayment', annual: -alloc.hecs, kind: 'value', show: withHecs && alloc.hecs > 0.5 },
    { key: 'net', label: 'Take-home pay', annual: alloc.net, kind: 'total' },
  ].filter((r) => r.show !== false);

  return {
    fileBase: `calcroo-income-breakdown-${fyLabel.replace(/[^0-9]/g, '-').replace(/-+/g, '-')}`,
    title: 'Income & Tax Breakdown',
    fyLabel,
    generatedAt: new Date(),
    meta: [
      { label: 'Financial year', value: `FY ${fyLabel}` },
      { label: 'Taxable income', value: money(alloc.salary) },
      { label: 'Residency', value: 'Australian resident' },
      { label: 'HECS-HELP debt', value: withHecs ? 'Yes' : 'No' },
      { label: 'Medicare levy', value: withMedicare ? 'Included (2%)' : 'Exempt' },
      { label: 'Total package (salary + super)', value: money(alloc.package) },
    ],
    rows,
    rates: {
      effective: alloc.effectiveRate,
      marginal: alloc.marginalRate,
      effectiveLabel: pct(alloc.effectiveRate),
      marginalLabel: pct(alloc.marginalRate),
    },
    allocation: {
      parts: (alloc.parts || []).map((p) => ({
        key: p.key,
        label: ALLOCATION_LABELS_EN[p.key] || p.key,
        color: ALLOCATION_COLORS[p.key] || '#5f6f66',
        value: p.value,
        pct: p.pct,
      })),
    },
    notes: [
      `Estimate only, for general information — not financial or tax advice. Based on FY ${fyLabel} Australian resident rates.`,
      'Income tax, Medicare levy and HECS-HELP are fixed figures generated by calcroo.au. If you change gross salary in this file, recalculate them at calcroo.au.',
      `Superannuation (${superPct}%) is paid by your employer on top of salary into your super fund; it is not part of take-home pay.`,
      'Generated at calcroo.au — free Australian tax & pay calculators.',
    ],
  };
}

export const _fmt = { money, pct };
